target-version = "py313"
include = ["bier", "tests", "setup.py"]

[lint.pydocstyle]
# Enforce numpy-style docstrings
convention = "numpy"

[lint.per-file-ignores]
# Ignore docstring requirements for test files
"tests/**/*.py" = ["D"]
# Ignore imported but unused
"**/__init__.py" = ["F401"]